// Markdown of the pinned report issue (US-DEV-11): verdict, averages, Mermaid charts and the day table.
import { averages, countable, dailyFlow, dayOf, REPORT_LABEL, TZ } from "./retro-lib.mjs";

// Starting values (assumption): six weeks fit a Mermaid x-axis, two weeks fit a table.
const CHART_DAYS = 42;
const TABLE_DAYS = 14;
const MARKER =
  "<!-- retro: generated by app/tools/workflow/actions/retro (US-DEV-11), do not edit by hand -->";

const one = (n) => n.toFixed(1);
const signed = (n, f = String) => (n > 0 ? `+${f(n)}` : f(n));

function verdict(avg) {
  if (!avg)
    return "**Trend: unknown.** Fewer than 2 full days since the kickoff day, so there is no average yet.";
  const { net } = avg.all;
  const recent = `last ${avg.last7.days} full days: ${signed(avg.last7.net, one)} per day`;
  if (Math.abs(net) < 0.05) return `**The backlog holds steady** (${recent}).`;
  const word = net > 0 ? "grows" : "shrinks";
  return `**The backlog ${word} by ${one(Math.abs(net))} issues per day** on average (${recent}).`;
}

function averagesTable(avg) {
  const cell = (part, key) =>
    avg ? (key === "net" ? signed(avg[part].net, one) : one(avg[part][key])) : "unknown";
  const head = avg
    ? `Overall (${avg.all.days} full days, ${avg.all.from} – ${avg.all.to}) | Last ${avg.last7.days} full days`
    : "Overall | Last 7 full days";
  return [
    `| Per day | ${head} |`,
    "| --- | --: | --: |",
    `| Created | ${cell("all", "created")} | ${cell("last7", "created")} |`,
    `| Closed | ${cell("all", "closed")} | ${cell("last7", "closed")} |`,
    `| Net | ${cell("all", "net")} | ${cell("last7", "net")} |`,
  ];
}

function niceMax(v) {
  if (v <= 0) return 1;
  const step = 10 ** Math.floor(Math.log10(v));
  return [1, 2, 2.5, 5, 10].map((m) => m * step).find((m) => m >= v);
}

function chart(palette, rows, max, series) {
  return [
    "```mermaid",
    `%%{init: {"themeVariables": {"xyChart": {"plotColorPalette": "${palette}"}}}}%%`,
    "xychart-beta",
    `  x-axis [${rows.map((r) => `"${r.day.slice(5)}"`).join(", ")}]`,
    `  y-axis "Issues" 0 --> ${niceMax(max)}`,
    ...series,
    "```",
  ];
}

function charts(days) {
  let created = 0;
  let closed = 0;
  const cumulative = days.map((r) => ({
    ...r,
    cc: (created += r.created),
    cx: (closed += r.closed),
  }));
  const rows = cumulative.slice(-CHART_DAYS);
  return [
    `## Created vs. closed (cumulative, last ${rows.length} days)`,
    "",
    "Orange: created, blue: closed. The gap between the two lines is the open backlog.",
    "",
    ...chart("#eb6834, #2a78d6", rows, rows.at(-1).cc, [
      `  line [${rows.map((r) => r.cc).join(", ")}]`,
      `  line [${rows.map((r) => r.cx).join(", ")}]`,
    ]),
    "",
    `## Open at the end of the day (burndown, last ${rows.length} days)`,
    "",
    ...chart("#eb6834", rows, Math.max(...rows.map((r) => r.open)), [
      `  bar [${rows.map((r) => r.open).join(", ")}]`,
    ]),
  ];
}

function dayTable(days) {
  return [
    `## Last ${Math.min(TABLE_DAYS, days.length)} days`,
    "",
    "| Day | Created | Closed | Net | Open at the end |",
    "| --- | --: | --: | --: | --: |",
    ...days
      .slice(-TABLE_DAYS)
      .reverse()
      .map(
        (r) =>
          `| ${r.day} | ${r.created} | ${r.closed} | ${signed(r.created - r.closed)} | ${r.open} |`,
      ),
  ];
}

/** Body of the report issue; the same issues on the same day always give the same text (no clock time). */
export function renderReport(allIssues, today) {
  const issues = allIssues.filter(countable);
  const days = dailyFlow(issues, today);
  const head = [
    MARKER,
    "",
    "> [!NOTE]",
    "> Generated report, rewritten by the workflow `retro.yml` (`make retro`) on every issue opened, closed or reopened and nightly.",
    "> **Not a work item. Do not claim, assign, edit or close it.** Spec: US-DEV-11.",
    "",
  ];
  if (!days.length) return [...head, "No issues yet."].join("\n") + "\n";
  const avg = averages(days);
  const open = days.at(-1).open;
  const latest = issues
    .flatMap((i) => [i.created_at, i.closed_at].filter(Boolean))
    .map(dayOf)
    .sort()
    .at(-1);
  return (
    [
      ...head,
      verdict(avg),
      "",
      ...averagesTable(avg),
      "",
      `Open now: **${open}** of ${issues.length} created (${Math.round((100 * open) / issues.length)} %).`,
      "",
      ...charts(days),
      "",
      ...dayTable(days),
      "",
      "---",
      "",
      `Source: the GitHub issues of this repository; pull requests and \`${REPORT_LABEL}\` issues are left out, "closed" includes closed as not planned. ` +
        `Days in ${TZ}. Averages leave out the kickoff day ${days[0].day} (${days[0].created} issues) and today. ` +
        `Data through ${today}, latest event ${latest}.`,
    ].join("\n") + "\n"
  );
}
