#!/usr/bin/env bash
# `make pr [PR=<n>]` (US-DEV-10): the step before a pull request goes to review. Regenerates the statistics block in
# README.md once per PR (not per commit), commits it if it changed, pushes the branch and marks the PR ready.
# Refuses, and changes nothing, on main/dev, a detached HEAD, a rebase/merge/cherry-pick/revert in progress or
# uncommitted changes: the numbers must describe exactly what the PR contains.
# Without PR=<n>, `gh` finds the PR of the current branch.
set -euo pipefail

pr="${1:-}"
here="$(cd "$(dirname "$0")" && pwd)"
root="$(git rev-parse --show-toplevel)"
cd "$root"

refuse() { echo "pr-ready: $1; nothing was changed" >&2; exit 1; }

branch="$(git symbolic-ref --short -q HEAD || true)"
case "$branch" in
  "") refuse "detached HEAD" ;;
  main | dev) refuse "branch $branch takes no direct commits (E-13)" ;;
esac
for op in rebase-merge rebase-apply MERGE_HEAD CHERRY_PICK_HEAD REVERT_HEAD; do
  [ -e "$(git rev-parse --git-path "$op")" ] && refuse "$op in progress"
done
[ -z "$(git status --porcelain)" ] || refuse "uncommitted changes (commit or remove them first)"

"$here/repo-stats.sh"
if git diff --quiet -- README.md; then
  echo "pr-ready: README statistics unchanged"
else
  git add README.md
  git commit -q -m "docs(dev): update repository statistics" -m "Generated by scripts/repo-stats.sh (make pr, US-DEV-10)."
  echo "pr-ready: committed the updated README statistics"
fi

git push
if [ -n "$pr" ]; then gh pr ready "$pr"; else gh pr ready; fi
