#!/usr/bin/env bash
# Repository statistics in README.md (US-DEV-10). Plain bash + git + awk, no network, no AI, well under a second.
# Branch-neutral so parallel branches rarely conflict on the block:
#   - tree numbers come from the index (what the commit will contain), large ones rounded to 3 significant digits;
#   - history numbers come from the merge base with origin/dev, identical for every branch cut from the same dev;
#   - no branch name, time stamp or hash in the output.
# Usage: scripts/repo-stats.sh          rewrite the block in README.md (working tree)
#        scripts/repo-stats.sh --hook   pre-commit mode: skip rules, writes to the index too
#        scripts/repo-stats.sh --print  print the block to stdout
# Opt-out for one commit: SKIP_REPO_STATS=1 git commit …
set -euo pipefail
export LC_ALL=C

mode="${1:-write}"
root="$(git rev-parse --show-toplevel)"
cd "$root"
readme="README.md"
start='<!-- repo-stats:start (generated by scripts/repo-stats.sh, do not edit by hand) -->'
end='<!-- repo-stats:end -->'

skip_reason() {
  [ "${SKIP_REPO_STATS:-0}" = 1 ] && { echo "SKIP_REPO_STATS=1"; return; }
  local branch op
  branch="$(git symbolic-ref --short -q HEAD || true)"
  case "$branch" in "") echo "detached HEAD"; return ;; main | dev) echo "branch $branch"; return ;; esac
  for op in rebase-merge rebase-apply MERGE_HEAD CHERRY_PICK_HEAD REVERT_HEAD; do
    [ -e "$(git rev-parse --git-path "$op")" ] && { echo "$op in progress"; return; }
  done
  true
}

# --- Tree (index) -------------------------------------------------------------------------------------
# "path<TAB>lines" for every text file in the index. README.md itself is left out, so the block never counts itself.
lines_per_file() { git grep --cached -I -c '' -- . ':!README.md' 2>/dev/null | sed 's/:\([0-9]*\)$/\t\1/' || true; }

# Large numbers to 3 significant digits ("233k"), as text (fmt) or as a number for charts (num).
AWK_ROUND='
function sig(n,  p) { if (n < 1000) return n; p = 10 ^ (int(log(n) / log(10)) - 2); return int(n / p + 0.5) * p }
function fmt(n,  v) { n = sig(n); if (n < 1000) return n; if (n < 1e6) { v = n / 1000; s = "k" } else { v = n / 1e6; s = "M" }
  return sprintf(v < 10 ? "%.2f" : v < 100 ? "%.1f" : "%.0f", v) s }'

tree_stats() {
  lines_per_file | awk -F'\t' "$AWK_ROUND"'
    function lang(p,  e) { e = p; sub(/.*\./, "", e)
      if (e ~ /^(ts|tsx|mts|cts)$/) return "TypeScript"; if (e ~ /^(js|mjs|cjs)$/) return "JavaScript"
      if (e == "md") return "Markdown"; if (e == "sql") return "SQL"; if (e == "sh") return "Shell"
      if (e ~ /^json5?$/) return "JSON"; if (e ~ /^ya?ml$/) return "YAML"; if (e == "css") return "CSS"
      if (e == "html") return "HTML"; if (e == "txt") return "Text"; return "Other" }
    { files++; total += $2; l = lang($1); by[l] += $2
      code = l ~ /^(TypeScript|JavaScript|SQL|Shell|CSS|HTML)$/
      if ($1 ~ /\.test\.(ts|tsx|mjs)$/ || $1 ~ /^app\/(packages\/)?e2e\//) test += $2
      else if (code) { prod += $2; if ($1 ~ /^app\/packages\/[^/]+\//) { split($1, a, "/"); pkg[a[3]] += $2 } } }
    END {
      printf "TOTAL\t%s\t%s\n", fmt(files), fmt(total)
      printf "RATIO\t%s\t%s\t%d\n", fmt(prod), fmt(test), prod ? int(100 * test / prod + 0.5) : 0
      for (l in by) printf "LANG\t%s\t%d\n", l, sig(by[l])
      for (p in pkg) printf "PKG\t%s\t%d\n", p, sig(pkg[p])
    }'
}

tracked_bytes() {
  git ls-files -s -- . ':!README.md' | awk '{print $2}' | git cat-file --batch-check='%(objectsize)' |
    awk '{s += $1} END { v = s / 1048576; printf (v < 10 ? "%.1f" : "%.0f") " MiB\n", v }'
}

count_files() { git ls-files -- "$@" | wc -l | tr -d ' '; }
count_matches() { local re="$1"; shift; git grep --cached -h -E "$re" -- "$@" 2>/dev/null | wc -l | tr -d ' '; }

# --- Specs (index) ------------------------------------------------------------------------------------
# "STORY<TAB>epic<TAB>status<TAB>id<TAB>title" and "FR<TAB>status".
spec_items() {
  git grep --cached -h -E '^### US-[A-Z]+-[0-9]+ ·|^\| FR-[A-Z]+-[0-9]+ ' -- 'Docs/PRODUCT-SPECS/*.md' 2>/dev/null |
    awk '
      # The product status is the first symbol; a story heading may carry the prototype status after it.
      function status(s) { sub(/^[ \t]+/, "", s); sub(/[ \t].*/, "", s)
        return s == "✅" ? "done" : s == "🟨" ? "wip" : s == "⛔" ? "dropped" : "planned" }
      /^###/ { n = split($0, f, " · "); id = f[1]; sub(/^### /, "", id); split(id, e, "-")
               printf "STORY\t%s\t%s\t%s\t%s\n", e[2], status(f[n]), id, f[2]; next }
      { n = split($0, c, "|"); printf "FR\t%s\n", status(c[n - 1]) }'
}

# "EPIC<TAB>code<TAB>name<TAB>spec file<TAB>description" from the spec index: names from the counter table
# ("| ACC Accounts | 5 | …"), file and description from the file table ("| [01-….md](…) | Epic ACC: … |").
epic_info() {
  git show :Docs/PRODUCT-SPECS/README.md 2>/dev/null | awk -F'|' '
    function trim(s) { gsub(/^[ \t]+|[ \t]+$/, "", s); return s }
    $2 ~ /^ [A-Z][A-Z]+ [^ ]/ && trim($3) ~ /^[0-9]+$/ { c = trim($2); code = c; sub(/ .*/, "", code); sub(/^[^ ]+ /, "", c)
      name[code] = c; order[++n] = code }
    trim($3) ~ /^Epic [A-Z]+: / { d = trim($3); code = d; sub(/^Epic /, "", code); sub(/:.*/, "", code); sub(/^Epic [A-Z]+: /, "", d)
      f = trim($2); sub(/^\[[^]]*\]\(/, "", f); sub(/\)$/, "", f); file[code] = f; desc[code] = toupper(substr(d, 1, 1)) substr(d, 2) }
    END { for (i = 1; i <= n; i++) { c = order[i]; printf "EPIC\t%s\t%s\t%s\t%s\n", c, name[c], file[c], desc[c] } }' || true
}

# One row per epic with stories: "rank<TAB>code<TAB>name<TAB>file<TAB>description<TAB>total<TAB>done<TAB>wip".
# rank orders done before in progress before planned, then by spec order.
epic_rows() {
  awk -F'\t' '
    $1 == "EPIC" { o[++n] = $2; name[$2] = $3; file[$2] = $4; desc[$2] = $5; next }
    $1 == "STORY" && $3 != "dropped" { t[$2]++; if ($3 == "done") d[$2]++; if ($3 == "wip") w[$2]++ }
    END { for (i = 1; i <= n; i++) { c = o[i]; if (!t[c]) continue
      r = d[c] == t[c] ? 1 : d[c] + w[c] ? 2 : 3
      printf "%d%02d\t%s\t%s\t%s\t%s\t%d\t%d\t%d\n", r, i, c, name[c], file[c], desc[c], t[c], d[c], w[c] } }' | sort
}

bar() { awk -v d="$1" -v w="$2" -v t="$3" 'BEGIN { if (!t) t = 1; a = int(10 * d / t + 0.5); b = int(10 * (d + w) / t + 0.5) - a
  for (i = 0; i < 10; i++) printf (i < a ? "█" : i < a + b ? "▒" : "░") }'; }

# Markdown table of epics; $1 = rows from epic_rows.
epic_table() {
  echo "| Status | Area | What it covers | Stories | Progress |"
  echo "| :-: | --- | --- | --- | --- |"
  local rank code name file desc t d w icon
  while IFS=$'\t' read -r rank code name file desc t d w; do
    [ -n "$code" ] || continue
    case "${rank:0:1}" in 1) icon="✅" ;; 2) icon="🟨" ;; *) icon="⬜" ;; esac
    printf '| %s | **%s** · [%s](Docs/PRODUCT-SPECS/%s) | %s | %d ✅ · %d 🟨 · %d ⬜ | `%s` |\n' \
      "$icon" "$name" "$code" "$file" "$desc" "$d" "$w" $((t - d - w)) "$(bar "$d" "$w" "$t")"
  done <<<"$1"
}

# --- History (merge base with origin/dev) -------------------------------------------------------------
history_base() {
  git rev-parse -q --verify HEAD >/dev/null || return 0
  git merge-base HEAD origin/dev 2>/dev/null || git rev-parse HEAD
}

days_chart() { # the 14 most recent days with commits; no date arithmetic (GNU and BSD date differ)
  local counts labels values
  counts="$(git log --format=%as "$1" | sort | uniq -c | tail -14)"
  labels="$(awk '{ printf "%s\"%s\"", (NR > 1 ? ", " : ""), substr($2, 6) }' <<<"$counts")"
  values="$(awk '{ printf "%s%d", (NR > 1 ? ", " : ""), $1 }' <<<"$counts")"
  printf '```mermaid\nxychart-beta\n  title "Commits on the last 14 active days"\n  x-axis [%s]\n  y-axis "Commits"\n  bar [%s]\n```\n' "$labels" "$values"
}

# --- Rendering ----------------------------------------------------------------------------------------
PROCESS_EPICS='^(QG|DEV)$' # quality gates and development process; everything else is the product

render() {
  local tree specs rows product process base
  tree="$(tree_stats)"
  specs="$(spec_items)"
  rows="$( { epic_info; printf '%s\n' "$specs"; } | epic_rows)"
  product="$(awk -F'\t' -v p="$PROCESS_EPICS" '$2 !~ p' <<<"$rows")"
  process="$(awk -F'\t' -v p="$PROCESS_EPICS" '$2 ~ p' <<<"$rows")"
  base="$(history_base)"
  local files lines prod test ratio
  IFS=$'\t' read -r _ files lines <<<"$(grep '^TOTAL' <<<"$tree")"
  IFS=$'\t' read -r _ prod test ratio <<<"$(grep '^RATIO' <<<"$tree")"

  echo "$start"
  echo
  echo "## What PflanzenDex does"
  echo
  local areas live wip_areas s_done s_wip s_total
  areas="$(grep -c . <<<"$product" || true)"
  live="$(grep -c '^1' <<<"$product" || true)"
  wip_areas="$(grep -c '^2' <<<"$product" || true)"
  read -r s_total s_done s_wip <<<"$(awk -F'\t' '{ t += $6; d += $7; w += $8 } END { print t + 0, d + 0, w + 0 }' <<<"$product")"
  echo "The product is cut into $areas feature areas (epics): **$live complete, $wip_areas in progress, $((areas - live - wip_areas)) planned.** Each area links to its spec; progress counts user stories (█ done, ▒ in progress, ░ planned)."
  echo
  epic_table "$product"
  echo
  echo '```mermaid'
  echo 'pie showData title Product user stories by status'
  printf '  "Done" : %d\n  "In progress" : %d\n  "Planned" : %d\n' "$s_done" "$s_wip" "$((s_total - s_done - s_wip))"
  echo '```'
  echo
  echo "## Engineering"
  echo
  local pkgs cases
  pkgs="$(grep '^PKG' <<<"$tree" | sort -t$'\t' -k3,3nr -k2,2 | awk -F'\t' "$AWK_ROUND"' { printf "%s%s %s", (NR > 1 ? " · " : ""), $2, fmt($3) }')"
  cases="$(count_matches '\b(it|test)(\.[a-z]+)?\(\s*["'\''`]' '*.test.ts' '*.test.tsx' '*.test.mjs')"
  echo "| | |"
  echo "| --- | --- |"
  echo "| **Repository** | $files files · $lines lines · $(tracked_bytes) |"
  echo "| **Production code** | $prod lines · packages: $pkgs |"
  echo "| **Tests** | $(count_files '*.test.ts' '*.test.tsx' '*.test.mjs') files · $(awk "$AWK_ROUND"' {print fmt($1)}' <<<"$cases") test cases · $test lines ($ratio% of production code) |"
  echo "| **Database** | $(count_files 'app/packages/db/migrations/*.sql') migrations · $(count_matches '^\s*"[a-z_]+\.[a-z_]+":' 'app/packages/core/src/kernel/error.ts') error codes |"
  echo "| **Process docs** | $(count_files 'Docs/decisions/[0-9]*.md') ADRs · $(count_files '.agents/skills/*/SKILL.md') agent skills · $(count_files 'Docs/operations/*.md') runbooks |"
  echo
  echo "### Quality gates and development process"
  echo
  epic_table "$process"
  echo
  echo '```mermaid'
  echo 'pie showData title Lines by language'
  grep '^LANG' <<<"$tree" | sort -t$'\t' -k3,3nr -k2,2 | awk -F'\t' 'NR <= 7 { printf "  \"%s\" : %d\n", $2, $3; next } { o += $3 } END { if (o) printf "  \"Other\" : %d\n", o }'
  echo '```'
  echo
  echo "## Activity"
  echo
  if [ -z "$base" ]; then
    echo "No commits yet."
  else
    local authors
    authors="$(git log --format=%aN "$base" | grep -v '\[bot\]$' | sort -u | wc -l | tr -d ' ')"
    printf '%s commits by %s people since %s · latest release `%s`\n' "$(git rev-list --count "$base")" "$authors" \
      "$(git log --reverse --format=%as "$base" | awk 'NR == 1')" "$(git describe --tags --abbrev=0 "$base" 2>/dev/null || echo none)"
    echo
    days_chart "$base"
  fi
  echo
  echo "<sub>Generated by \`scripts/repo-stats.sh\` before every commit (US-DEV-10). Code numbers come from the committed files, rounded to 3 significant digits; activity comes from \`dev\` up to this branch's base.</sub>"
  echo
  echo "$end"
}

# --- Writing ------------------------------------------------------------------------------------------
splice() { # README text on stdin, block in file $1
  awk -v s="$start" -v e="$end" -v f="$1" '
    $0 == s { while ((getline l < f) > 0) print l; skip = 1; found = 1; next }
    $0 == e { skip = 0; next }
    !skip { print }
    END { if (!found) exit 3 }'
}

main() {
  if [ "$mode" = --print ]; then render; return; fi
  if [ "$mode" = --hook ]; then
    local why; why="$(skip_reason)"
    [ -n "$why" ] && { echo "repo-stats: skipped ($why)" >&2; return 0; }
  fi
  [ -f "$readme" ] || { echo "repo-stats: $readme is missing" >&2; return 1; }
  tmp="$(mktemp)"; trap 'rm -f "$tmp" "$tmp.new"' EXIT
  render >"$tmp"

  # Hook with unstaged README edits: update the index only and leave the working tree to the developer.
  if [ "$mode" = --hook ] && git ls-files --error-unmatch "$readme" >/dev/null 2>&1 && ! git diff --quiet -- "$readme"; then
    git show ":$readme" | splice "$tmp" >"$tmp.new" || { echo "repo-stats: markers missing in staged $readme" >&2; return 1; }
    git show ":$readme" | cmp -s - "$tmp.new" && return 0
    git update-index --cacheinfo "100644,$(git hash-object -w "$tmp.new"),$readme"
    echo "repo-stats: updated the staged $readme only (it has unstaged edits)" >&2
    return 0
  fi
  splice "$tmp" <"$readme" >"$tmp.new" || { echo "repo-stats: markers missing in $readme" >&2; return 1; }
  if ! cmp -s "$readme" "$tmp.new"; then
    cat "$tmp.new" >"$readme"
    echo "repo-stats: updated $readme" >&2
  fi
  if [ "$mode" = --hook ]; then git add -- "$readme"; fi
}

main
