#!/usr/bin/env bash
# Repository statistics in README.md (US-DEV-10). Plain bash + git + awk, no network, no AI, well under a second.
# Branch-neutral so parallel branches rarely conflict on the block:
#   - tree numbers come from the index (what the commit will contain), large ones rounded to 3 significant digits;
#   - history numbers come from the merge base with origin/dev, identical for every branch cut from the same dev;
#   - no branch name, time stamp or hash in the output.
# Usage: scripts/repo-stats.sh          rewrite the block in README.md (working tree)
#        scripts/repo-stats.sh --hook   pre-commit mode: skip rules, writes to the index too
#        scripts/repo-stats.sh --print  print the block to stdout
# Opt-out for one commit: SKIP_REPO_STATS=1 git commit …
set -euo pipefail
export LC_ALL=C

mode="${1:-write}"
root="$(git rev-parse --show-toplevel)"
cd "$root"
readme="README.md"
start='<!-- repo-stats:start (generated by scripts/repo-stats.sh, do not edit by hand) -->'
end='<!-- repo-stats:end -->'

skip_reason() {
  [ "${SKIP_REPO_STATS:-0}" = 1 ] && { echo "SKIP_REPO_STATS=1"; return; }
  local branch op
  branch="$(git symbolic-ref --short -q HEAD || true)"
  case "$branch" in "") echo "detached HEAD"; return ;; main | dev) echo "branch $branch"; return ;; esac
  for op in rebase-merge rebase-apply MERGE_HEAD CHERRY_PICK_HEAD REVERT_HEAD; do
    [ -e "$(git rev-parse --git-path "$op")" ] && { echo "$op in progress"; return; }
  done
  true
}

# --- Tree (index) -------------------------------------------------------------------------------------
# "path<TAB>lines" for every text file in the index. README.md itself is left out, so the block never counts itself.
lines_per_file() { git grep --cached -I -c '' -- . ':!README.md' 2>/dev/null | sed 's/:\([0-9]*\)$/\t\1/' || true; }

# Large numbers to 3 significant digits ("233k"), as text (fmt) or as a number for charts (num).
AWK_ROUND='
function sig(n,  p) { if (n < 1000) return n; p = 10 ^ (int(log(n) / log(10)) - 2); return int(n / p + 0.5) * p }
function fmt(n,  v) { n = sig(n); if (n < 1000) return n; if (n < 1e6) { v = n / 1000; s = "k" } else { v = n / 1e6; s = "M" }
  return sprintf(v < 10 ? "%.2f" : v < 100 ? "%.1f" : "%.0f", v) s }'

tree_stats() {
  lines_per_file | awk -F'\t' "$AWK_ROUND"'
    function lang(p,  e) { e = p; sub(/.*\./, "", e)
      if (e ~ /^(ts|tsx|mts|cts)$/) return "TypeScript"; if (e ~ /^(js|mjs|cjs)$/) return "JavaScript"
      if (e == "md") return "Markdown"; if (e == "sql") return "SQL"; if (e == "sh") return "Shell"
      if (e ~ /^json5?$/) return "JSON"; if (e ~ /^ya?ml$/) return "YAML"; if (e == "css") return "CSS"
      if (e == "html") return "HTML"; if (e == "txt") return "Text"; return "Other" }
    { files++; total += $2; l = lang($1); by[l] += $2
      code = l ~ /^(TypeScript|JavaScript|SQL|Shell|CSS|HTML)$/
      if ($1 ~ /\.test\.(ts|tsx|mjs)$/ || $1 ~ /^app\/e2e\//) test += $2; else if (code) prod += $2
      if (code && $1 ~ /^app\/packages\/[^/]+\//) { split($1, a, "/"); pkg[a[3]] += $2 } }
    END {
      printf "TOTAL\t%s\t%s\n", fmt(files), fmt(total)
      printf "RATIO\t%s\t%s\t%d\n", fmt(prod), fmt(test), prod ? int(100 * test / prod + 0.5) : 0
      for (l in by) printf "LANG\t%s\t%d\n", l, sig(by[l])
      for (p in pkg) printf "PKG\t%s\t%d\n", p, sig(pkg[p])
    }'
}

tracked_bytes() {
  git ls-files -s -- . ':!README.md' | awk '{print $2}' | git cat-file --batch-check='%(objectsize)' |
    awk '{s += $1} END { v = s / 1048576; printf (v < 10 ? "%.1f" : "%.0f") " MiB\n", v }'
}

count_files() { git ls-files -- "$@" | wc -l | tr -d ' '; }
count_matches() { local re="$1"; shift; git grep --cached -h -E "$re" -- "$@" 2>/dev/null | wc -l | tr -d ' '; }

# --- Specs (index) ------------------------------------------------------------------------------------
# "STORY<TAB>epic<TAB>status<TAB>id<TAB>title" and "FR<TAB>status".
spec_items() {
  git grep --cached -h -E '^### US-[A-Z]+-[0-9]+ ·|^\| FR-[A-Z]+-[0-9]+ ' -- 'Docs/PRODUCT-SPECS/*.md' 2>/dev/null |
    awk '
      # The product status is the first symbol; a story heading may carry the prototype status after it.
      function status(s) { sub(/^[ \t]+/, "", s); sub(/[ \t].*/, "", s)
        return s == "✅" ? "done" : s == "🟨" ? "wip" : s == "⛔" ? "dropped" : "planned" }
      /^###/ { n = split($0, f, " · "); id = f[1]; sub(/^### /, "", id); split(id, e, "-")
               printf "STORY\t%s\t%s\t%s\t%s\n", e[2], status(f[n]), id, f[2]; next }
      { n = split($0, c, "|"); printf "FR\t%s\n", status(c[n - 1]) }'
}

# Epic names from the counter table of the spec index ("| ACC Accounts | 5 | …").
epic_names() { git show :Docs/PRODUCT-SPECS/README.md 2>/dev/null | sed -n 's/^| \([A-Z]\{2,4\}\) \([^|]*[^ |]\) *| [0-9].*/\1\t\2/p' || true; }

bar() { awk -v d="$1" -v w="$2" -v t="$3" 'BEGIN { if (!t) t = 1; a = int(10 * d / t + 0.5); b = int(10 * (d + w) / t + 0.5) - a
  for (i = 0; i < 10; i++) printf (i < a ? "█" : i < a + b ? "▒" : "░") }'; }

# --- History (merge base with origin/dev) -------------------------------------------------------------
history_base() {
  git rev-parse -q --verify HEAD >/dev/null || return 0
  git merge-base HEAD origin/dev 2>/dev/null || git rev-parse HEAD
}

days_chart() { # the 14 most recent days with commits; no date arithmetic (GNU and BSD date differ)
  local counts labels values
  counts="$(git log --format=%as "$1" | sort | uniq -c | tail -14)"
  labels="$(awk '{ printf "%s\"%s\"", (NR > 1 ? ", " : ""), substr($2, 6) }' <<<"$counts")"
  values="$(awk '{ printf "%s%d", (NR > 1 ? ", " : ""), $1 }' <<<"$counts")"
  printf '```mermaid\nxychart-beta\n  title "Commits on the last 14 active days"\n  x-axis [%s]\n  y-axis "Commits"\n  bar [%s]\n```\n' "$labels" "$values"
}

# --- Rendering ----------------------------------------------------------------------------------------
render() {
  local tree specs names base
  tree="$(tree_stats)"
  specs="$(spec_items)"
  names="$(epic_names)"
  base="$(history_base)"
  local files lines prod test ratio
  IFS=$'\t' read -r _ files lines <<<"$(grep '^TOTAL' <<<"$tree")"
  IFS=$'\t' read -r _ prod test ratio <<<"$(grep '^RATIO' <<<"$tree")"

  echo "$start"
  echo
  echo "_Generated by \`scripts/repo-stats.sh\` before every commit (US-DEV-10). Tree numbers come from the committed files, rounded to 3 significant digits; history numbers come from \`dev\` up to this branch's base._"
  echo
  echo "### At a glance"
  echo
  echo "| Size | Code | Quality | Process |"
  echo "| --- | --- | --- | --- |"
  local cases; cases="$(count_matches '\b(it|test)(\.[a-z]+)?\(\s*["'\''`]' '*.test.ts' '*.test.tsx' '*.test.mjs')"
  printf '| %s files | %s lines of production code | %s test files | %s ADRs |\n' "$files" "$prod" \
    "$(count_files '*.test.ts' '*.test.tsx' '*.test.mjs')" "$(count_files 'Docs/decisions/[0-9]*.md')"
  printf '| %s lines | %s packages · %s migrations | %s test cases | %s skills |\n' "$lines" \
    "$(git ls-files app/packages | cut -d/ -f3 | sort -u | wc -l | tr -d ' ')" \
    "$(count_files 'app/packages/db/migrations/*.sql')" "$(awk "$AWK_ROUND"' {print fmt($1)}' <<<"$cases")" \
    "$(count_files '.agents/skills/*/SKILL.md')"
  printf '| %s tracked | %s error codes | %s lines of tests (%s%% of code) | %s runbooks |\n' "$(tracked_bytes)" \
    "$(count_matches '^\s*"[a-z_]+\.[a-z_]+":' 'app/packages/core/src/kernel/error.ts')" "$test" "$ratio" \
    "$(count_files 'Docs/operations/*.md')"
  echo

  local s_done s_wip s_plan s_total f_done f_wip f_total
  s_total="$(grep -c '^STORY' <<<"$specs" || true)"
  s_done="$(grep -c '^STORY.*	done	' <<<"$specs" || true)"
  s_wip="$(grep -c '^STORY.*	wip	' <<<"$specs" || true)"
  s_plan=$((s_total - s_done - s_wip))
  f_total="$(grep -c '^FR' <<<"$specs" || true)"
  f_done="$(grep -c '^FR	done' <<<"$specs" || true)"
  f_wip="$(grep -c '^FR	wip' <<<"$specs" || true)"
  echo "### Product progress"
  echo
  echo "$s_total user stories and $f_total functional requirements in \`Docs/PRODUCT-SPECS/\`. Stories: $s_done ✅ done, $s_wip 🟨 in progress, $s_plan ⬜ planned. Requirements: $f_done ✅, $f_wip 🟨."
  echo
  echo "| Epic | Stories | ✅ | 🟨 | ⬜ | Progress |"
  echo "| --- | --: | --: | --: | --: | --- |"
  awk -F'\t' '$1 == "STORY" { if (!($2 in t)) o[++n] = $2; t[$2]++; if ($3 == "done") d[$2]++; if ($3 == "wip") w[$2]++ }
    END { for (i = 1; i <= n; i++) { e = o[i]; printf "%s\t%d\t%d\t%d\n", e, t[e], d[e], w[e] } }' <<<"$specs" |
    while IFS=$'\t' read -r e t d w; do
      local name; name="$(awk -F'\t' -v e="$e" '$1 == e {print $2}' <<<"$names")"
      printf '| %s %s | %d | %d | %d | %d | `%s` |\n' "$e" "$name" "$t" "$d" "$w" $((t - d - w)) "$(bar "$d" "$w" "$t")"
    done
  echo
  echo '```mermaid'
  echo 'pie showData title User stories by status'
  printf '  "Done" : %d\n  "In progress" : %d\n  "Planned" : %d\n' "$s_done" "$s_wip" "$s_plan"
  echo '```'
  echo
  echo "### Notable features"
  echo
  echo "Stories marked done (✅) in the spec:"
  echo
  awk -F'\t' '$1 == "STORY" && $3 == "done" { printf "- **%s** %s\n", $4, $5 }' <<<"$specs"
  echo
  echo "<details><summary>$s_wip stories in progress (🟨)</summary>"
  echo
  awk -F'\t' '$1 == "STORY" && $3 == "wip" { printf "- **%s** %s\n", $4, $5 }' <<<"$specs"
  echo
  echo "</details>"
  echo
  echo "### Code"
  echo
  echo '```mermaid'
  echo 'pie showData title Lines by language'
  grep '^LANG' <<<"$tree" | sort -t$'\t' -k3,3nr -k2,2 | awk -F'\t' 'NR <= 7 { printf "  \"%s\" : %d\n", $2, $3; next } { o += $3 } END { if (o) printf "  \"Other\" : %d\n", o }'
  echo '```'
  echo
  echo "| Package | Lines of code |"
  echo "| --- | --: |"
  grep '^PKG' <<<"$tree" | sort -t$'\t' -k3,3nr -k2,2 | awk -F'\t' "$AWK_ROUND"' { printf "| `%s` | %s |\n", $2, fmt($3) }'
  echo

  echo "### History"
  echo
  if [ -z "$base" ]; then
    echo "No commits yet."
  else
    local commits authors first release
    commits="$(git rev-list --count "$base")"
    authors="$(git log --format=%aN "$base" | grep -v '\[bot\]$' | sort -u | wc -l | tr -d ' ')"
    first="$(git log --reverse --format=%as "$base" | awk 'NR == 1')"
    release="$(git describe --tags --abbrev=0 "$base" 2>/dev/null || echo none)"
    echo "$commits commits by $authors people since $first. Latest release: \`$release\`."
    echo
    days_chart "$base"
    echo
    echo '```mermaid'
    echo 'pie showData title Commits by Conventional Commit type'
    git log --format=%s "$base" | sed -n 's/^\([a-z]*\)\(([^)]*)\)\{0,1\}!\{0,1\}:.*/\1/p' | sort | uniq -c | sort -k1,1nr -k2,2 |
      awk '{ printf "  \"%s\" : %d\n", $2, $1 }'
    echo '```'
    echo
    echo "Latest features:"
    echo
    git log --format=%s "$base" | awk '/^feat(\(|!|:)/ && n++ < 5 { print "- " $0 } END { if (!n) print "- none yet" }'
  fi
  echo
  echo "$end"
}

# --- Writing ------------------------------------------------------------------------------------------
splice() { # README text on stdin, block in file $1
  awk -v s="$start" -v e="$end" -v f="$1" '
    $0 == s { while ((getline l < f) > 0) print l; skip = 1; found = 1; next }
    $0 == e { skip = 0; next }
    !skip { print }
    END { if (!found) exit 3 }'
}

main() {
  if [ "$mode" = --print ]; then render; return; fi
  if [ "$mode" = --hook ]; then
    local why; why="$(skip_reason)"
    [ -n "$why" ] && { echo "repo-stats: skipped ($why)" >&2; return 0; }
  fi
  [ -f "$readme" ] || { echo "repo-stats: $readme is missing" >&2; return 1; }
  tmp="$(mktemp)"; trap 'rm -f "$tmp" "$tmp.new"' EXIT
  render >"$tmp"

  # Hook with unstaged README edits: update the index only and leave the working tree to the developer.
  if [ "$mode" = --hook ] && git ls-files --error-unmatch "$readme" >/dev/null 2>&1 && ! git diff --quiet -- "$readme"; then
    git show ":$readme" | splice "$tmp" >"$tmp.new" || { echo "repo-stats: markers missing in staged $readme" >&2; return 1; }
    git show ":$readme" | cmp -s - "$tmp.new" && return 0
    git update-index --cacheinfo "100644,$(git hash-object -w "$tmp.new"),$readme"
    echo "repo-stats: updated the staged $readme only (it has unstaged edits)" >&2
    return 0
  fi
  splice "$tmp" <"$readme" >"$tmp.new" || { echo "repo-stats: markers missing in $readme" >&2; return 1; }
  if ! cmp -s "$readme" "$tmp.new"; then
    cat "$tmp.new" >"$readme"
    echo "repo-stats: updated $readme" >&2
  fi
  if [ "$mode" = --hook ]; then git add -- "$readme"; fi
}

main
