// Tests for scripts/repo-stats.sh (US-DEV-10) against a throwaway git repository.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT = fileURLToPath(new URL("../../scripts/repo-stats.sh", import.meta.url));
const START = "<!-- repo-stats:start (generated by scripts/repo-stats.sh, do not edit by hand) -->";
const END = "<!-- repo-stats:end -->";
const ENV = {
  ...process.env,
  GIT_AUTHOR_NAME: "Test",
  GIT_AUTHOR_EMAIL: "test@example.org",
  GIT_COMMITTER_NAME: "Test",
  GIT_COMMITTER_EMAIL: "test@example.org",
  GIT_AUTHOR_DATE: "2026-10-01T12:00:00Z",
  GIT_COMMITTER_DATE: "2026-10-01T12:00:00Z",
  SKIP_REPO_STATS: "",
};

function git(dir, ...args) {
  return execFileSync("git", args, { cwd: dir, env: ENV, encoding: "utf8" });
}

function stats(dir, ...args) {
  const r = spawnSync("bash", [SCRIPT, ...args], { cwd: dir, env: ENV, encoding: "utf8" });
  return { code: r.status, out: r.stdout, err: r.stderr };
}

function write(dir, file, text) {
  mkdirSync(path.dirname(path.join(dir, file)), { recursive: true });
  writeFileSync(path.join(dir, file), text);
}

/** Repo with a spec, a test, a feat commit on dev and a feature branch checked out. */
function fixture(t) {
  const dir = mkdtempSync(path.join(tmpdir(), "repo-stats-"));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  git(dir, "init", "-q", "-b", "dev");
  write(dir, "README.md", `# Demo\n\n${START}\n${END}\n`);
  write(
    dir,
    "Docs/PRODUCT-SPECS/01-Demo.md",
    "### US-ABC-01 · Water a plant · ✅ new\n### US-ABC-02 · Measure growth · ⬜ ✅\n| FR-ABC-01 | Rule | 🟨 |\n",
  );
  write(dir, "Docs/PRODUCT-SPECS/02-Xyz.md", "### US-XYZ-01 · Add a friend · ✅ new\n");
  write(dir, "Docs/PRODUCT-SPECS/19-Dev.md", "### US-DEV-01 · Run tasks · 🟨 new\n");
  write(
    dir,
    "Docs/PRODUCT-SPECS/README.md",
    [
      "| [01-Demo.md](01-Demo.md) | Epic ABC: watering, growth |",
      "| [02-Xyz.md](02-Xyz.md)   | Epic XYZ: friends          |",
      "| [19-Dev.md](19-Dev.md)   | Epic DEV: hooks            |",
      "| ABC Demo epic  | 2 | 0 | 2 |",
      "| XYZ Other epic | 1 | 0 | 1 |",
      "| DEV Process    | 1 | 0 | 1 |",
      "",
    ].join("\n"),
  );
  write(dir, "app/packages/core/src/a.ts", "export const a = 1;\n");
  write(dir, "app/packages/core/src/a.test.ts", 'it("works", () => {});\n');
  git(dir, "add", ".");
  git(dir, "commit", "-q", "-m", "feat(abc): water a plant (US-ABC-01)");
  git(dir, "update-ref", "refs/remotes/origin/dev", "HEAD");
  git(dir, "switch", "-q", "-c", "feat/abc-02-growth");
  return dir;
}

const readme = (dir) => readFileSync(path.join(dir, "README.md"), "utf8");

test("US-DEV-10: the block shows the feature areas with status, description, spec link and progress", (t) => {
  const { code, out } = stats(fixture(t), "--print");
  assert.equal(code, 0);
  assert.match(out, /2 feature areas \(epics\): \*\*1 complete, 1 in progress, 0 planned\.\*\*/);
  const xyz =
    "| ✅ | **Other epic** · [XYZ](Docs/PRODUCT-SPECS/02-Xyz.md) | Friends | 1 ✅ · 0 🟨 · 0 ⬜ | `██████████` |";
  const abc =
    "| 🟨 | **Demo epic** · [ABC](Docs/PRODUCT-SPECS/01-Demo.md) | Watering, growth | 1 ✅ · 0 🟨 · 1 ⬜ | `█████░░░░░` |";
  assert.ok(out.includes(xyz), "a complete area");
  assert.ok(out.includes(abc), "the prototype ✅ after ⬜ is not the product status");
  assert.ok(out.indexOf(xyz) < out.indexOf(abc), "complete areas come first");
  assert.match(out, /"Done" : 2\n {2}"In progress" : 0\n {2}"Planned" : 1/);
});

test("US-DEV-10: process epics are listed under engineering, not as product features", (t) => {
  const out = stats(fixture(t), "--print").out;
  const engineering = out.indexOf("## Engineering");
  const dev = out.indexOf(
    "**Process** · [DEV](Docs/PRODUCT-SPECS/19-Dev.md) | Hooks | 0 ✅ · 1 🟨 · 0 ⬜",
  );
  assert.ok(engineering > 0 && dev > engineering);
});

test("US-DEV-10: the block reports code, tests and activity", (t) => {
  const out = stats(fixture(t), "--print").out;
  assert.match(out, /\| \*\*Repository\*\* \| 6 files · 13 lines · /);
  assert.match(out, /\| \*\*Production code\*\* \| 1 lines · packages: core 1 \|/);
  assert.match(
    out,
    /\| \*\*Tests\*\* \| 1 files · 1 test cases · 1 lines \(100% of production code\) \|/,
  );
  assert.match(out, /1 commits by 1 people since 2026-10-01/);
  assert.match(out, /```mermaid\npie showData title Lines by language/);
  assert.match(out, /```mermaid\nxychart-beta/);
});

test("US-DEV-10: no branch name, time stamp or hash in the block; two runs give the same output", (t) => {
  const dir = fixture(t);
  const first = stats(dir, "--print").out;
  assert.equal(stats(dir, "--print").out, first);
  assert.doesNotMatch(first, /abc-02-growth/);
  assert.ok(!first.includes(git(dir, "rev-parse", "--short", "HEAD").trim()));
});

test("US-DEV-10: history comes from the merge base with origin/dev, not from the branch's own commits", (t) => {
  const dir = fixture(t);
  const before = stats(dir, "--print").out;
  write(dir, "notes.txt", "x\n");
  git(dir, "add", ".");
  git(dir, "commit", "-q", "-m", "feat(abc): branch-only work");
  const after = stats(dir, "--print").out;
  const history = (s) => s.slice(s.indexOf("## Activity"));
  assert.equal(history(after), history(before));
  assert.doesNotMatch(after, /branch-only work/);
});

test("US-DEV-10: tree numbers come from the index, and README.md never counts itself", (t) => {
  const dir = fixture(t);
  write(dir, "unstaged.ts", "const x = 1;\n");
  assert.match(stats(dir, "--print").out, /\| 6 files · 13 lines/);
  git(dir, "add", "unstaged.ts");
  assert.match(stats(dir, "--print").out, /\| 7 files · 14 lines/);
  write(dir, "README.md", `# Demo\n\nmore\nlines\n\n${START}\n${END}\n`);
  git(dir, "add", "README.md");
  assert.match(stats(dir, "--print").out, /\| 7 files · 14 lines/);
});

test("US-DEV-10: the hook writes the block, stages README.md, and a second run changes nothing", (t) => {
  const dir = fixture(t);
  const r = stats(dir, "--hook");
  assert.equal(r.code, 0, r.err);
  assert.match(readme(dir), /## What PflanzenDex does/);
  assert.match(readme(dir), /^# Demo\n/);
  assert.equal(git(dir, "diff", "--name-only").trim(), "", "README.md is staged");
  const once = readme(dir);
  assert.equal(stats(dir, "--hook").code, 0);
  assert.equal(readme(dir), once);
});

test("US-DEV-10: the hook is skipped on dev, on main, when detached and on SKIP_REPO_STATS=1", (t) => {
  const dir = fixture(t);
  for (const setup of [
    () => git(dir, "switch", "-q", "dev"),
    () => git(dir, "switch", "-q", "-c", "main"),
    () => git(dir, "switch", "-q", "--detach"),
  ]) {
    setup();
    const r = stats(dir, "--hook");
    assert.equal(r.code, 0);
    assert.match(r.err, /repo-stats: skipped/);
    assert.equal(readme(dir), `# Demo\n\n${START}\n${END}\n`);
  }
  git(dir, "switch", "-q", "feat/abc-02-growth");
  const r = spawnSync("bash", [SCRIPT, "--hook"], {
    cwd: dir,
    env: { ...ENV, SKIP_REPO_STATS: "1" },
    encoding: "utf8",
  });
  assert.match(r.stderr, /skipped \(SKIP_REPO_STATS=1\)/);
});

test("US-DEV-10: the hook is skipped while a merge is in progress", (t) => {
  const dir = fixture(t);
  writeFileSync(path.join(dir, ".git/MERGE_HEAD"), git(dir, "rev-parse", "HEAD"));
  assert.match(stats(dir, "--hook").err, /skipped \(MERGE_HEAD in progress\)/);
});

test("US-DEV-10: with unstaged README edits the hook updates only the staged version", (t) => {
  const dir = fixture(t);
  const edited = `# Demo, edited\n\n${START}\n${END}\n`;
  write(dir, "README.md", edited);
  const r = stats(dir, "--hook");
  assert.equal(r.code, 0, r.err);
  assert.match(r.err, /updated the staged README.md only/);
  assert.equal(readme(dir), edited);
  const staged = git(dir, "show", ":README.md");
  assert.match(staged, /^# Demo\n/);
  assert.match(staged, /## What PflanzenDex does/);
});

test("US-DEV-10: missing markers are reported with a non-zero exit, never silently", (t) => {
  const dir = fixture(t);
  write(dir, "README.md", "# Demo without markers\n");
  const r = stats(dir);
  assert.equal(r.code, 1);
  assert.match(r.err, /markers missing in README.md/);
  assert.equal(readme(dir), "# Demo without markers\n");
});

test("US-DEV-10: without origin/dev the history falls back to HEAD", (t) => {
  const dir = fixture(t);
  git(dir, "update-ref", "-d", "refs/remotes/origin/dev");
  const r = stats(dir, "--print");
  assert.equal(r.code, 0, r.err);
  assert.match(r.out, /1 commits by 1 people/);
});
