// Tests for scripts/repo-stats.sh and scripts/pr-ready.sh (US-DEV-10) against a throwaway git repository.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { chmodSync, mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT = fileURLToPath(new URL("../../scripts/repo-stats.sh", import.meta.url));
const PR_READY = fileURLToPath(new URL("../../scripts/pr-ready.sh", import.meta.url));
const START = "<!-- repo-stats:start (generated by scripts/repo-stats.sh, do not edit by hand) -->";
const END = "<!-- repo-stats:end -->";
const ENV = {
  ...process.env,
  GIT_AUTHOR_NAME: "Test",
  GIT_AUTHOR_EMAIL: "test@example.org",
  GIT_COMMITTER_NAME: "Test",
  GIT_COMMITTER_EMAIL: "test@example.org",
  GIT_AUTHOR_DATE: "2026-10-01T12:00:00Z",
  GIT_COMMITTER_DATE: "2026-10-01T12:00:00Z",
};

function git(dir, ...args) {
  return execFileSync("git", args, { cwd: dir, env: ENV, encoding: "utf8" });
}

function stats(dir, ...args) {
  const r = spawnSync("bash", [SCRIPT, ...args], { cwd: dir, env: ENV, encoding: "utf8" });
  return { code: r.status, out: r.stdout, err: r.stderr };
}

function write(dir, file, text) {
  mkdirSync(path.dirname(path.join(dir, file)), { recursive: true });
  writeFileSync(path.join(dir, file), text);
}

/** Repo with a spec, a test, a feat commit on dev and a feature branch checked out. */
function fixture(t) {
  const dir = mkdtempSync(path.join(tmpdir(), "repo-stats-"));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  git(dir, "init", "-q", "-b", "dev");
  write(dir, "README.md", `# Demo\n\n${START}\n${END}\n`);
  write(
    dir,
    "Docs/PRODUCT-SPECS/01-Demo.md",
    "### US-ABC-01 · Water a plant · ✅ new\n### US-ABC-02 · Measure growth · ⬜ ✅\n| FR-ABC-01 | Rule | 🟨 |\n",
  );
  write(dir, "Docs/PRODUCT-SPECS/02-Xyz.md", "### US-XYZ-01 · Add a friend · ✅ new\n");
  write(dir, "Docs/PRODUCT-SPECS/19-Dev.md", "### US-DEV-01 · Run tasks · 🟨 new\n");
  write(
    dir,
    "Docs/PRODUCT-SPECS/README.md",
    [
      "| [01-Demo.md](01-Demo.md) | Epic ABC: watering, growth |",
      "| [02-Xyz.md](02-Xyz.md)   | Epic XYZ: friends          |",
      "| [19-Dev.md](19-Dev.md)   | Epic DEV: hooks            |",
      "| ABC Demo epic  | 2 | 0 | 2 |",
      "| XYZ Other epic | 1 | 0 | 1 |",
      "| DEV Process    | 1 | 0 | 1 |",
      "",
    ].join("\n"),
  );
  write(dir, "app/packages/core/src/a.ts", "export const a = 1;\n");
  write(dir, "app/packages/core/src/a.test.ts", 'it("works", () => {});\n');
  git(dir, "add", ".");
  git(dir, "commit", "-q", "-m", "feat(abc): water a plant (US-ABC-01)");
  git(dir, "update-ref", "refs/remotes/origin/dev", "HEAD");
  git(dir, "switch", "-q", "-c", "feat/abc-02-growth");
  return dir;
}

const readme = (dir) => readFileSync(path.join(dir, "README.md"), "utf8");

test("US-DEV-10: the block shows the feature areas with status, description, spec link and progress", (t) => {
  const { code, out } = stats(fixture(t), "--print");
  assert.equal(code, 0);
  assert.match(out, /2 feature areas \(epics\): \*\*1 complete, 1 in progress, 0 planned\.\*\*/);
  const xyz =
    "| ✅ | **Other epic** · [XYZ](Docs/PRODUCT-SPECS/02-Xyz.md) | Friends | 1 ✅ · 0 🟨 · 0 ⬜ | `██████████` |";
  const abc =
    "| 🟨 | **Demo epic** · [ABC](Docs/PRODUCT-SPECS/01-Demo.md) | Watering, growth | 1 ✅ · 0 🟨 · 1 ⬜ | `█████░░░░░` |";
  assert.ok(out.includes(xyz), "a complete area");
  assert.ok(out.includes(abc), "the prototype ✅ after ⬜ is not the product status");
  assert.ok(out.indexOf(xyz) < out.indexOf(abc), "complete areas come first");
  assert.match(out, /"Done" : 2\n {2}"In progress" : 0\n {2}"Planned" : 1/);
});

test("US-DEV-10: process epics are listed under engineering, not as product features", (t) => {
  const out = stats(fixture(t), "--print").out;
  const engineering = out.indexOf("## Engineering");
  const dev = out.indexOf(
    "**Process** · [DEV](Docs/PRODUCT-SPECS/19-Dev.md) | Hooks | 0 ✅ · 1 🟨 · 0 ⬜",
  );
  assert.ok(engineering > 0 && dev > engineering);
});

test("US-DEV-10: the block reports code, tests and activity", (t) => {
  const out = stats(fixture(t), "--print").out;
  assert.match(out, /\| \*\*Repository\*\* \| 6 files · 13 lines · /);
  assert.match(out, /\| \*\*Production code\*\* \| 1 lines · packages: core 1 \|/);
  assert.match(
    out,
    /\| \*\*Tests\*\* \| 1 files · 1 test cases · 1 lines \(100% of production code\) \|/,
  );
  assert.match(out, /1 commits by 1 people since 2026-10-01/);
  assert.match(out, /```mermaid\npie showData title Lines by language/);
  assert.match(out, /```mermaid\nxychart-beta/);
});

test("US-DEV-10: no branch name, time stamp or hash in the block; two runs give the same output", (t) => {
  const dir = fixture(t);
  const first = stats(dir, "--print").out;
  assert.equal(stats(dir, "--print").out, first);
  assert.doesNotMatch(first, /abc-02-growth/);
  assert.ok(!first.includes(git(dir, "rev-parse", "--short", "HEAD").trim()));
});

test("US-DEV-10: history comes from the merge base with origin/dev, not from the branch's own commits", (t) => {
  const dir = fixture(t);
  const before = stats(dir, "--print").out;
  write(dir, "notes.txt", "x\n");
  git(dir, "add", ".");
  git(dir, "commit", "-q", "-m", "feat(abc): branch-only work");
  const after = stats(dir, "--print").out;
  const history = (s) => s.slice(s.indexOf("## Activity"));
  assert.equal(history(after), history(before));
  assert.doesNotMatch(after, /branch-only work/);
});

test("US-DEV-10: tree numbers come from the index, and README.md never counts itself", (t) => {
  const dir = fixture(t);
  write(dir, "unstaged.ts", "const x = 1;\n");
  assert.match(stats(dir, "--print").out, /\| 6 files · 13 lines/);
  git(dir, "add", "unstaged.ts");
  assert.match(stats(dir, "--print").out, /\| 7 files · 14 lines/);
  write(dir, "README.md", `# Demo\n\nmore\nlines\n\n${START}\n${END}\n`);
  git(dir, "add", "README.md");
  assert.match(stats(dir, "--print").out, /\| 7 files · 14 lines/);
});

/** The fixture with an `origin` to push to and a fake `gh` that records its arguments. */
function prFixture(t) {
  const dir = fixture(t);
  const origin = mkdtempSync(path.join(tmpdir(), "repo-stats-origin-"));
  const bin = mkdtempSync(path.join(tmpdir(), "repo-stats-bin-"));
  t.after(() => {
    rmSync(origin, { recursive: true, force: true });
    rmSync(bin, { recursive: true, force: true });
  });
  git(origin, "init", "-q", "--bare");
  git(dir, "remote", "add", "origin", origin);
  git(dir, "push", "-q", "-u", "origin", "feat/abc-02-growth");
  writeFileSync(path.join(bin, "gh"), `#!/bin/sh\necho "$@" >> "${bin}/gh.log"\n`);
  chmodSync(path.join(bin, "gh"), 0o755);
  const run = (...args) => {
    const r = spawnSync("bash", [PR_READY, ...args], {
      cwd: dir,
      env: { ...ENV, PATH: `${bin}:${process.env.PATH}` },
      encoding: "utf8",
    });
    return { code: r.status, out: r.stdout, err: r.stderr };
  };
  const ghCalls = () => {
    try {
      return readFileSync(path.join(bin, "gh.log"), "utf8").trim().split("\n");
    } catch {
      return [];
    }
  };
  return { dir, origin, run, ghCalls };
}

test("US-DEV-10: make pr leaves README.md alone, pushes and marks the PR ready", (t) => {
  const { dir, origin, run, ghCalls } = prFixture(t);
  const before = readme(dir);
  const head = git(dir, "rev-parse", "HEAD");
  const r = run("42");
  assert.equal(r.code, 0, r.err);
  assert.equal(readme(dir), before, "no statistics block is written per PR");
  assert.equal(git(dir, "rev-parse", "HEAD"), head, "no commit is made");
  assert.equal(git(origin, "rev-parse", "feat/abc-02-growth"), head, "the branch is pushed");
  assert.deepEqual(ghCalls(), ["pr ready 42"]);

  const again = run();
  assert.equal(again.code, 0, again.err);
  assert.equal(git(dir, "rev-parse", "HEAD"), head);
  assert.deepEqual(ghCalls(), ["pr ready 42", "pr ready"]);
});

test("US-DEV-10: make pr refuses on dev, on main and when detached, and changes nothing", (t) => {
  const { dir, run, ghCalls } = prFixture(t);
  for (const [setup, reason] of [
    [() => git(dir, "switch", "-q", "dev"), /branch dev/],
    [() => git(dir, "switch", "-q", "-c", "main"), /branch main/],
    [() => git(dir, "switch", "-q", "--detach"), /detached HEAD/],
  ]) {
    setup();
    const r = run();
    assert.equal(r.code, 1);
    assert.match(r.err, reason);
    assert.match(r.err, /nothing was changed/);
    assert.equal(readme(dir), `# Demo\n\n${START}\n${END}\n`);
  }
  assert.deepEqual(ghCalls(), []);
});

test("US-DEV-10: make pr refuses with uncommitted changes or while a merge is in progress", (t) => {
  const { dir, run, ghCalls } = prFixture(t);
  write(dir, "notes.txt", "draft\n");
  const dirty = run();
  assert.equal(dirty.code, 1);
  assert.match(dirty.err, /uncommitted changes/);
  rmSync(path.join(dir, "notes.txt"));
  writeFileSync(path.join(dir, ".git/MERGE_HEAD"), git(dir, "rev-parse", "HEAD"));
  const merging = run();
  assert.equal(merging.code, 1);
  assert.match(merging.err, /MERGE_HEAD in progress/);
  assert.equal(readme(dir), `# Demo\n\n${START}\n${END}\n`);
  assert.deepEqual(ghCalls(), []);
});

test("US-DEV-10: missing markers are reported with a non-zero exit, never silently", (t) => {
  const dir = fixture(t);
  write(dir, "README.md", "# Demo without markers\n");
  const r = stats(dir);
  assert.equal(r.code, 1);
  assert.match(r.err, /markers missing in README.md/);
  assert.equal(readme(dir), "# Demo without markers\n");
});

test("US-DEV-10: without origin/dev the history falls back to HEAD", (t) => {
  const dir = fixture(t);
  git(dir, "update-ref", "-d", "refs/remotes/origin/dev");
  const r = stats(dir, "--print");
  assert.equal(r.code, 0, r.err);
  assert.match(r.out, /1 commits by 1 people/);
});
